def build_doctor_report_html(doctor, appointments, treatments=None, start_date = None, end_date=None):

    if isinstance(treatments, (str, type(None))) and hasattr(treatments, 'strftime'):
        end_date = start_date
        start_date = treatments
        treatments = []

    treatments = treatments or []
    start_str = start_date.strftime('%Y-%m-%d') if start_date else "Unknown"
    end_str = end_date.strftime('%Y-%m-%d') if end_date else "Unknown"

    return f"""
    <html>
    <body style="font-family:Arial, sans-serif;">
        <h2 style="color: #333;">Monthly Activity Report</h2>
        <p><strong>Doctor:</strong> Dr. {doctor.user.name}</p>
        <p><strong>Period:</strong> {start_str} to {end_str}</p>

        <hr>
        <h3 style="color: #555;">Summary</h3>
        <ul>
            <li><strong>Total Appointments:</strong> {len(appointments)}</li>
            <li><strong>Total treatments Recorded:</strong> {len(treatments)}</li>
        </ul>

        <h3 style="color: #555;">Appointment Log</h3>
        <table style="width: 100%; border-collapse: collapse;">
            <tr style="background-color: #f2f2f2;">
                <th style="border: 1px solid #ddd; padding: 8px; text-align: left;">Date</th>
                <th style="border: 1px solid #ddd; padding: 8px; text-align: left;">Time</th>
                <th style="border: 1px solid #ddd; padding: 8px; text-align: left;">Status</th>
            </tr>
            {"".join([
                f'<tr><td style="border: 1px solid #ddd; padding: 8px;">{a.appointment_date}</td>'
                f'<td style="border: 1px solid #ddd; padding: 8px;">{a.appointment_time}</td>'
                f'<td style="border: 1px solid #ddd; padding: 8px;">{a.status}</td></tr>' 
                for a in appointments[:20] 
            ])}
        </table>
        { "<p><em>(Showing last 20 records)</em><p>" if len(appointments) > 20 else "" }
        
        <br>
        <p style="color: #888; font-size:12px;"> Generated by HMS</p>
    </body>
    </html>
    """
    
    